version: '2'
services:
  db:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      # TODO: for dev
      MYSQL_DATABASE: school
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - data:/var/lib/mysql
  backend:
    build: .
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true
    links:
      - db
    volumes:
      - ./backend:/go/src