version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.0
      - image: circleci/mysql:5.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: mv ./backend /go/src/backend
      - run:
        name: run test
        command: go test -run ''
        working_directory: /go/src/backend