version: 2.1

jobs:
  build:
    docker:
      # Circle CIに自分のプロジェクトをビルドする時にはどのDockerイメージを使うのかを伝えている
      - image: circleci/golang:1.12.0
        environment:
          GO111MODULE: "on"
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: circle_test
          DB_NAME_TEST: circle_test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
    # これなんだっけ？
    working_directory: ~/repo
    # stepsのrunで実行するコマンドを指定していく
    steps:
      # checkoutってなんだ？
      # CircleCIがGitHubのレポジトリをチェックアウトし、作成した仮想環境にクローンするらしい
      - checkout
      # これなんだっけ？
      - run: mv ./backend /go/src/backend
      - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      # restore_cashe??
      # - restore_cache:
      #     keys:
      #       - go-mod-v1-{{ checksum "/go/src/backend/go.sum" }}
      - run:
          name: run test
          command: go test -run ''
          working_directory: /go/src/backend
      - run: go get -u github.com/reviewdog/reviewdog/cmd/reviewdog
      - run:
          name: reviewdog
          command: golangci-lint run --issues-exit-code 0 --out-format checkstyle ./... | reviewdog -name=golangci-lint -f=checkstyle -reporter=github-pr-check 2>&1
          working_directory: /go/src/backend
