version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.0
        environment:
          GO111MODULE: "on"
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: circle_test
          DB_NAME_TEST: circle_test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
    working_directory: ~/repo
    steps:
      - checkout
      - run: mv ./backend /go/src/backend
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "/go/src/backend/go.sum" }}
      - run:
          name: run test
          command: go test -run ''
          working_directory: /go/src/backend