version: 2.1

general:
  artifacts:
    - "result.txt"

jobs:
  build:
    docker:
      # Circle CIに自分のプロジェクトをビルドする時にはどのDockerイメージを使うのかを伝えている
      - image: circleci/golang:1.12.0
        environment:
          GO111MODULE: "on"
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: circle_test
          DB_NAME_TEST: circle_test
          REVIEWDOG_VERSION: 0.9.12
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
    # 作業ディレクトリをrepoにする
    working_directory: ~/repo
    # stepsのrunで実行するコマンドを指定していく
    steps:
      # checkoutってなんだ？
      # CircleCIがGitHubのレポジトリをチェックアウトし、作成した仮想環境にクローンするらしい
      - checkout
      - run: mv ./backend /go/src/backend
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "/go/src/backend/go.sum" }}
            - golangci-lint
            - reviewdog
      - run:
          name: go build
          command: go build main.go
          working_directory: /go/src/backend
      - run:
          name: install golangci_lint
          command: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - save_cache:
          key: golangci-lint
          paths:
            - /go/bin/golangci-lint
      - run:
          name: run golangci-lint
          command: |
            golangci-lint run \
              --issues-exit-code 0 \
              --out-format checkstyle \
              ./...
          working_directory: /go/src/backend
      # - run:
      #     name: run test
      #     command: go test -run ''
      #     working_directory: /go/src/backend
      - run:
          name: install reviewdog
          command: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s  v$REVIEWDOG_VERSION
      - save_cache:
          key: reviewdog
          paths:
            - ./bin/reviewdog
      - run:
          name: run review dog
          command: |
            golangci-lint run \
              --tests=false \
              --issues-exit-code 0 \
              --out-format checkstyle \
              -E dupl \
              -E goconst \
              -E gocyclo --gocyclo.min-complexity 15 \
              ./... > ~/repo/result.txt
            cd ~/repo
            cat ~/repo/result.txt | ./bin/reviewdog -f=checkstyle -diff="git diff" -reporter='github-pr-review'
          working_directory: /go/src/backend
      - run:
          name: run review dog
          command: |
            golangci-lint run --issues-exit-code 0 --out-format checkstyle ./... > ~/repo/result.txt
            cd ~/repo
            cat ~/repo/result.txt | ./bin/reviewdog -name=golangci-lint -f=checkstyle -diff="git diff" -reporter='github-pr-check'
          working_directory: /go/src/backend
      - save_cache:
          key: go-mod-v1-{{ checksum "/go/src/backend/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts:
          path: ~/repo/result.txt
          destination: result.txt